export const ADD_PERSON = "ADD_PERSON";
export const REMOVE_PERSON = "REMOVE_PERSON";
export const SET_LOCATION = "SET_LOCATION";
export const CHANGE_SELECTION = "CHANGE_SELECTION";
export const CLEAR_SELECTED_PERSONNEL = "CLEAR_SELECTED_PERSONNEL";