export const RESET_APP = 'RESET_APP';
export const RESET_INCIDENT = 'RESET_INCIDENT';

export const ADD_PERSON = 'ADD_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';

export const SET_LOCATION = 'SET_LOCATION';

export const TOGGLE_SELECTED_PERSON = 'TOGGLE_SELECTED_PERSON';
export const CLEAR_SELECTED_PERSONNEL = 'CLEAR_SELECTED_PERSONNEL';

export const EDIT_NAME = 'EDIT_NAME';
export const ADD_GROUP = 'ADD_GROUP';
export const REMOVE_GROUP = 'REMOVE_GROUP';

export const START_INCIDENT = 'START_INCIDENT';
export const END_INCIDENT = 'END_INCIDENT';

export const NEW_USER = 'NEW_USER';