/**
 * All redux types
 */

export const RESET_APP = 'RESET_APP';
export const RESET_INCIDENT = 'RESET_INCIDENT';

export const START_INCIDENT = 'START_INCIDENT';
export const END_INCIDENT = 'END_INCIDENT';
export const RESUME_INCIDENT = 'RESUME_INCIDENT';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const TO_HOME_STACK = 'TO_HOME_STACK';
export const TO_INCIDENT_STACK = 'TO_INCIDENT_STACK';
export const TO_END_STACK = 'TO_END_STACK';

export const ADD_PERSON = 'ADD_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';
export const SET_PERSON_LOCATION_ID = 'SET_PERSON_LOCATION_ID';
export const CLEAR_PERSONNEL = 'CLEAR_PERSONNEL';

export const SET_NAME = 'SET_NAME';
export const SET_VISIBILITY = 'SET_VISIBILITY';
export const INIT_GROUP = 'INIT_GROUP';

export const TOGGLE_SELECTED_PERSON = 'TOGGLE_SELECTED_PERSON';
export const SELECT_PERSON = 'SELECT_PERSON';
export const DESELECT_PERSON = 'DESELECT_PERSON';
export const CLEAR_SELECTED_PERSONNEL = 'CLEAR_SELECTED_PERSONNEL';

export const TOGGLE_THEME = 'TOGGLE_THEME';
