/**
 * All redux types
 */

export const RESET_APP = 'RESET_APP';
export const RESET_INCIDENT = 'RESET_INCIDENT';
export const UPDATE_CONFIGURATION = 'UPDATE_CONFIGURATION';

export const START_INCIDENT = 'START_INCIDENT';
export const END_INCIDENT = 'END_INCIDENT';
export const RESUME_INCIDENT = 'RESUME_INCIDENT';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const TO_HOME_STACK = 'TO_HOME_STACK';
export const TO_INCIDENT_STACK = 'TO_INCIDENT_STACK';
export const TO_END_STACK = 'TO_END_STACK';

export const ADD_PERSON = 'ADD_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';
export const MOVE_PERSON = 'MOVE_PERSON';
export const CONFIGURE_PERSONNEL = 'CONFIGURE_PERSONNEL';

export const EDIT_GROUP = 'EDIT_GROUP';
export const ALERT_PERSON_TO_GROUP = 'ALERT_PERSON_TO_GROUP';
export const DEALERT_PERSON_TO_GROUP = 'DEALERT_PERSON_TO_GROUP';
export const TOGGLE_GROUP = 'TOGGLE_GROUP';
export const CONFIGURE_GROUPS = 'CONFIGURE_GROUPS';

export const TOGGLE_PERSON = 'TOGGLE_PERSON';
export const SELECT_PERSON = 'SELECT_PERSON';
export const DESELECT_PERSON = 'DESELECT_PERSON';
export const CLEAR_SELECTED_PERSONNEL = 'CLEAR_SELECTED_PERSONNEL';
export const TOGGLE_GROUP_MODE = 'TOGGLE_GROUP_MODE';
export const CLEAR_SELECTED_GROUP_MODE = 'CLEAR_SELECTED_GROUP_MODE';

export const TOGGLE_THEME = 'TOGGLE_THEME';
